# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile for WhoAmI MCP Server
FROM python:3.13-slim

# Install dependencies
WORKDIR /app
# Copy dependency declarations
COPY pyproject.toml uv.lock ./
RUN pip install --no-cache-dir pip setuptools
# Install our package (and dependencies)
COPY . .
RUN pip install --no-cache-dir .

# Default command to start the MCP server
CMD ["python", "main.py"]
